### ISSUE TITLE
Helpdesk - user-facing improvements

### ISSUE THREAD

**Issue by mikesname** [mikesname/docview#471]
- write some explanatory documentation
   - clarify helpdesk is *not* a real person (or an AI)
   - clarify does not actually answer question, just suggest which institution it should be directed to
   - clarify difference between repository search and helpdesk query
   - what kind of questions should be used?
 - put in context of other EHRI portal help
 - rename to something else
 - show full list of institutions available (in the helpdesk) and somehow allow a user query to order them)

**Comment by mikesname** [comment]
@retosp I have:

 - added the list of available institutions to the helpdesk
 - made a few more improvements to the UI

Feel free to add any changes you see fit here.

**Comment by retosp** [comment]
Hi Mike,
I think it looks much better/clearer now. A couple of suggestions to improve the supplied texts further. Could these be implemented quickly so that we can get them translated this week?

- Replace the follwoing string "The helpdesk will attempt to match your query to the EHRI partner institution best placed to answer it. " with "The helpdesk will attempt to match your question to the EHRI partner institution best placed to answer it. Please note that the helpdesk will not provide you with an answer to your question, nor will it directly send your question to an EHRI partner institution . For more information about the helpdesk, see here [link to the "What is the purpose of the helpdesk" FAQ if possible]".



- Replace the existing string in the query box "Enter your query here. Subject-specific terms are best." with "Enter your question [strong]in English[/strong] here. Provide details about the area of archival research that your question relates to, for instance, place names, personal names, instiutions or subject terms."

**Comment by retosp** [comment]
On the result screen, change the following string "Recommended contacts ordered by relevance for your query:" with "Recommended instiutions ordered by relevance for your question. Please use the email address provided to contact one or several relevant instiution(s)"
