### ISSUE TITLE
Guides: new pages don't save

### ISSUE THREAD

**Issue by michalfrankl** [mikesname/docview#516]
Currently, in the research guides, new pages or pages with changed URL don't save and result into the nondescript error message.

**Comment by mikesname** [comment]
Sorry, this is more MySQL weirdness. Since I changed the table to Unicode the existing varchar columns don't seem long enough. Might have to wait till tomorrow for a fix since I'm traveling today.

As a test, could you try a short name/title and see if it saves?

In case you're wondering, we only use mysql for the guides and predictable account data, hence all these stupid bugs.

**Comment by michalfrankl** [comment]
Yes, you are right, saving a page called "Org" worked.

**Comment by mikesname** [comment]
I think you should have at least 64 characters, if that helps ;)

Unfortunately, since the server version is old just increasing the varchar length won't work, since it's already at the max. And to change it to text I have to drop the index and re-create the column, which is slightly more involved.

**Comment by mikesname** [comment]
Fixed in ae77805729e062b27aa161e246c9ebe315ef787a.
